- hosts: all
  connection: local
  become: yes
  tasks:
    - name: Install
      pip:
        name: jumeaux
        executable: '{{ bin.pip3 }}'

    - name: Create symbolic link
      file:
        src: '/usr/bin/python3'
        dest: '/usr/bin/python'
        state: link
