- hosts: all
  connection: local
  become: yes
  vars:
    document_root: /usr/share/nginx/html
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      notify: Restart nginx

    - name: Copy sample logs, configs, and dummy responsies used by Jumeaux
      become: no
      copy:
        src: '../vagrant/'
        dest: '/home/vagrant/'

    - name: Create symlinks to nginx document root
      file:
        src: '/home/vagrant'
        dest: '{{ document_root }}/api'
        force: yes
        state: link

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
